version: '3.8'
services:
  wattsup:
    image: wattsup:1.0-dev
    build:
      context: ..
      dockerfile: dockerfile
      target: dev
    container_name: "wattsup-cont"
    hostname: "wattsup-cont"
    command: "sleep infinity"
    environment:
      - "PYTHONPATH=/opt/code/backend"
    volumes:
      - "../..:/opt/code"
      - "../../data:/mnt/data"
      - "../../test_data:/mnt/test_data"
    ports:
      - "8000:8080"